<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Harinder" failures="1" tests="5" name="Test" time="27.094" errors="0" timestamp="2023-01-11T00:52:36 GMT-07:00">
  <testcase classname="com.naveenautomation.Tests.MyAccountTest" name="testSomething" time="0.025">
    <skipped/>
  </testcase> <!-- testSomething -->
  <testcase classname="com.naveenautomation.Tests.MyAccountTest" name="testSomething" time="0.0">
    <skipped/>
  </testcase> <!-- testSomething -->
  <testcase classname="com.naveenautomation.Tests.MyAccountTest" name="testSomething" time="0.002">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at com.naveenautomation.Tests.MyAccountTest.testSomething(MyAccountTest.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testSomething -->
  <testcase classname="com.naveenautomation.Tests.MyAccountTest" name="validateLogin" time="0.079"/>
  <testcase classname="com.naveenautomation.Tests.MyAccountTest" name="verifyAlertBannerForTelephoneUpdate" time="0.0">
    <skipped/>
  </testcase> <!-- verifyAlertBannerForTelephoneUpdate -->
</testsuite> <!-- Test -->
